version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - mongo
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDbSettings__ConnectionString=mongodb://mongo:27017
      - ElasticSearchSettings__Uri=http://elasticsearch:9200

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  elasticsearch:
    image: elasticsearch:8.5.0  # Используем публичный образ
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false  # Отключаем security для простоты
    ports:
      - "9200:9200"

volumes:
  mongo_data: